name: Temperature Daily Export

on:
  schedule:
    - cron: '59 23 * * *'  # Cada dia a les 23:59
  workflow_dispatch:       # ➕ Aquesta línia permet executar manualment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositori
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instal·lar dependències
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script
        run: python main.py

      - name: Fer commit i push del JSON
        run: |
          git config user.name "arnarpuvi"
          git config user.email "arnarpuvi@users.noreply.github.com"
          git add temp_*.json
          git commit -m "Afegit arxiu de temperatura del dia $(date +%Y-%m-%d)" || echo "Sense canvis"
          git push
