name: Temperature Daily Export

on:
  push:
  schedule:
    - cron: '*/5 * * * *'  # Cada 5 minuts

jobs:
  export-temperature:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositori
        uses: actions/checkout@v3

      - name: Instal·lar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instal·lar dependències (si n'hi ha)
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Executar script
        run: python temperatures.py

      - name: Fer commit i push del fitxer JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add temp_*.json
          git commit -m "Dades temperatura per $(date +%Y-%m-%d)" || echo "Sense canvis"
          git push
